//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Ufba.visualForm
{
	/// <summary>
	/// DomainModel visualFormDomainModel
	/// Description for Ufba.visualForm.visualForm
	/// </summary>
	[DslDesign::DisplayNameResource("Ufba.visualForm.visualFormDomainModel.DisplayName", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Ufba.visualForm.visualFormDomainModel.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("c8af8293-d69f-4584-989c-50394575205f")]
	public partial class visualFormDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// visualFormDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xc8af8293, 0xd69f, 0x4584, 0x98, 0x9c, 0x50, 0x39, 0x45, 0x75, 0x20, 0x5f);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public visualFormDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(FormModel),
				typeof(Form),
				typeof(Field),
				typeof(Option),
				typeof(FormModelHasElements),
				typeof(FormHasFields),
				typeof(FieldHasOptions),
				typeof(visualFormDiagram),
				typeof(FieldConnector),
				typeof(OptionConnector),
				typeof(FormShape),
				typeof(FieldShape),
				typeof(OptionShape),
				typeof(global::Ufba.visualForm.FixUpDiagram),
				typeof(global::Ufba.visualForm.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Form), "Name", Form.NameDomainPropertyId, typeof(Form.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Field), "Name", Field.NameDomainPropertyId, typeof(Field.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Field), "Type", Field.TypeDomainPropertyId, typeof(Field.TypePropertyHandler)),
				new DomainMemberInfo(typeof(Field), "Required", Field.RequiredDomainPropertyId, typeof(Field.RequiredPropertyHandler)),
				new DomainMemberInfo(typeof(Option), "Name", Option.NameDomainPropertyId, typeof(Option.NamePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(FormModelHasElements), "FormModel", FormModelHasElements.FormModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(FormModelHasElements), "Element", FormModelHasElements.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(FormHasFields), "Form", FormHasFields.FormDomainRoleId),
				new DomainRolePlayerInfo(typeof(FormHasFields), "Field", FormHasFields.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(FieldHasOptions), "Field", FieldHasOptions.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(FieldHasOptions), "Option", FieldHasOptions.OptionDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(10);
				createElementMap.Add(typeof(FormModel), 0);
				createElementMap.Add(typeof(Form), 1);
				createElementMap.Add(typeof(Field), 2);
				createElementMap.Add(typeof(Option), 3);
				createElementMap.Add(typeof(visualFormDiagram), 4);
				createElementMap.Add(typeof(FieldConnector), 5);
				createElementMap.Add(typeof(OptionConnector), 6);
				createElementMap.Add(typeof(FormShape), 7);
				createElementMap.Add(typeof(FieldShape), 8);
				createElementMap.Add(typeof(OptionShape), 9);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Ufba.visualForm.visualFormDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new FormModel(partition, propertyAssignments);
				case 1: return new Form(partition, propertyAssignments);
				case 2: return new Field(partition, propertyAssignments);
				case 3: return new Option(partition, propertyAssignments);
				case 4: return new visualFormDiagram(partition, propertyAssignments);
				case 5: return new FieldConnector(partition, propertyAssignments);
				case 6: return new OptionConnector(partition, propertyAssignments);
				case 7: return new FormShape(partition, propertyAssignments);
				case 8: return new FieldShape(partition, propertyAssignments);
				case 9: return new OptionShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(3);
				createElementLinkMap.Add(typeof(FormModelHasElements), 0);
				createElementLinkMap.Add(typeof(FormHasFields), 1);
				createElementLinkMap.Add(typeof(FieldHasOptions), 2);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Ufba.visualForm.visualFormDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new FormModelHasElements(partition, roleAssignments, propertyAssignments);
				case 1: return new FormHasFields(partition, roleAssignments, propertyAssignments);
				case 2: return new FieldHasOptions(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Ufba.visualForm.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return visualFormDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (visualFormDomainModel.resourceManager == null)
				{
					visualFormDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(visualFormDomainModel).Assembly);
				}
				return visualFormDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return visualFormDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return visualFormDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (visualFormDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new visualFormCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					visualFormDomainModel.copyClosure = copyFilter;
				}
				return visualFormDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (visualFormDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new visualFormDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					visualFormDomainModel.removeClosure = removeFilter;
				}
				return visualFormDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Ufba.visualForm.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::Ufba.visualForm.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Ufba.visualForm.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::Ufba.visualForm.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class visualFormDeleteClosure : visualFormDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public visualFormDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class visualFormDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public visualFormDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Ufba.visualForm.FormModelHasElements.ElementDomainRoleId, true);
			DomainRoles.Add(global::Ufba.visualForm.FormHasFields.FieldDomainRoleId, true);
			DomainRoles.Add(global::Ufba.visualForm.FieldHasOptions.OptionDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class visualFormCopyClosure : visualFormCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public visualFormCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class visualFormCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public visualFormCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace Ufba.visualForm
{
	/// <summary>
	/// DomainEnumeration: FieldType
	/// Description for Ufba.visualForm.FieldType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FieldType
	{
		/// <summary>
		/// text
		/// Description for Ufba.visualForm.FieldType.text
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/text.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		text,
		/// <summary>
		/// integer
		/// Description for Ufba.visualForm.FieldType.integer
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/integer.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		integer,
		/// <summary>
		/// date
		/// Description for Ufba.visualForm.FieldType.date
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/date.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		date,
		/// <summary>
		/// email
		/// Description for Ufba.visualForm.FieldType.email
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/email.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		email,
		/// <summary>
		/// check
		/// Description for Ufba.visualForm.FieldType.check
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/check.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		check,
		/// <summary>
		/// radio
		/// Description for Ufba.visualForm.FieldType.radio
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/radio.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		radio,
		/// <summary>
		/// textarea
		/// Description for Ufba.visualForm.FieldType.textarea
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/textarea.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		textarea,
		/// <summary>
		/// selectBox
		/// Description for Ufba.visualForm.FieldType.selectBox
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/selectBox.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		selectBox,
		/// <summary>
		/// comboBox
		/// Description for Ufba.visualForm.FieldType.comboBox
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/comboBox.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		comboBox,
		/// <summary>
		/// file
		/// Description for Ufba.visualForm.FieldType.file
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.FieldType/file.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		file,
	}
}
namespace Ufba.visualForm
{
	/// <summary>
	/// DomainEnumeration: Order
	/// Description for Ufba.visualForm.Order
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Order
	{
		/// <summary>
		/// ASC
		/// Description for Ufba.visualForm.Order.ASC
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.Order/ASC.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		ASC,
		/// <summary>
		/// DESC
		/// Description for Ufba.visualForm.Order.DESC
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.visualForm.Order/DESC.Description", typeof(global::Ufba.visualForm.visualFormDomainModel), "Ufba.visualForm.GeneratedCode.DomainModelResx")]
		DESC,
	}
}

