//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ufba.visualForm
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "vForm";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"visualForm";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Ufba";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID visualFormDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(visualFormCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID visualFormExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(visualFormCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewvisualFormExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(visualFormCommandSetId), 0x0001);
	
		// Package identifier
		public const string visualFormPackageId = "a3bfe338-0dc8-4aa8-8a41-56820c85dbac";
		
		// Editor factory identifier
		public const string visualFormEditorFactoryId = "7b28abd5-fdc0-4dc1-aa74-593b0377e735";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string visualFormModelExplorerToolWindowId = "e1fe9fcd-33d9-4314-9387-3384f415a58b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Ufba.visualForm
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string visualFormCommandSetId = "2a872bc7-e581-4ead-a45f-49f90e831ca6";
	}
}